traefik:
  image: traefik:latest
  command: --configFile=/var/traefik/traefik.toml
  ports:
    - "443:443"
    - "8090:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/traefik.toml:/var/traefik/traefik.toml 
    - $PWD/acme:/etc/acme

whoami1:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:traefik.senodio.com"

whoami2:
  image: emilevauge/whoami
  labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:traefik.senodio.com"